services:
  elastic:
    build:
      context: .
      dockerfile: Dockerfile-es
    ports:
      - 9200:9200 # 9200번 포트에서 Elasticsearch 실행
    environment:
      # 아래 설정은 개발/테스트 환경에서 간단하게 테스트하기 위한 옵션 (운영 환경에서는 설정하면 안 됨)
      - discovery.type=single-node # 단일 노드 (지금은 알 필요 없음)
      - xpack.security.enabled=false # 보안 설정
      - xpack.security.http.ssl.enabled=false # 보안 설정
      - ES_JAVA_OPTS=-Xms4g -Xmx4g # Elasticsearch JVM 메모리 설정
      - indices.queries.cache.size=10%  # JVM 힙의 10%
      - indices.fielddata.cache.size=20%  # Nori 분석 캐싱
    volumes:
      - es_data:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.4 # 8.17.4 버전
    ports:
      - 5601:5601 # 5601번 포트에서 kibana 실행
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200 # kibana에게 통신할 Elasticsearch 주소 알려주기

volumes:
  es_data:

